name: 'DataVault MSSQL'
description: 'DataVault MSSQL Example'
id: '414e96d9-5aec-461c-7a0f-08db36925815'
configuration:
  id: 'biGENIUS.Implementation.Generator.Datavault.Mssql'
  version: '1.0.0'
sourceSystems:
  - name: 'dynamics'
    description: 'anything'
    id: 'fc062872-ebd8-49a7-9771-058828f26b20'
  - name: 'blackforestmarkets'
    description: 'anything'
    id: '41225553-9471-4504-ac6f-86325c233378'
version: 'v1.1'
